# Generated by Django 4.2.6 on 2023-11-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_account_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pigeonpackageuser",
            name="personal_info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pigeonpackageuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="/img/default_profile_pic.jpg",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
