# Generated by Django 4.2.6 on 2023-11-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_account_app", "0002_pigeonpackageuser_personal_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pigeonpackageuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default/default_profile_pic.jpg",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
