# Generated by Django 4.2.6 on 2023-11-03 14:29

from django.db import migrations, models
import pigeon_package_account_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_account_app", "0003_alter_pigeonpackageuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pigeonpackageuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default=pigeon_package_account_app.models.get_default_profile_picture,
                null=True,
                upload_to=pigeon_package_account_app.models.get_profile_picture_filepath,
            ),
        ),
    ]
