# Generated by Django 4.2.6 on 2023-11-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="package",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="pigeon_package_main_app.package",
            ),
            preserve_default=False,
        ),
    ]
