# Generated by Django 4.2.6 on 2023-11-04 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_main_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="textfile",
            old_name="folder",
            new_name="package",
        ),
        migrations.AlterUniqueTogether(
            name="textfile",
            unique_together={("name", "package")},
        ),
    ]
