# Generated by Django 4.2.6 on 2023-11-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_main_app", "0002_rename_folder_textfile_package_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textfile",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
