# Generated by Django 4.2.6 on 2023-11-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_main_app", "0002_file_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="height",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="file",
            name="width",
            field=models.IntegerField(default=0),
        ),
    ]
