# Generated by Django 4.2.6 on 2023-11-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_main_app", "0003_alter_textfile_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="textfile",
            name="font_size",
            field=models.PositiveIntegerField(default=12, null=True),
        ),
    ]
