# Generated by Django 4.2.6 on 2023-11-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_main_app", "0003_alter_file_height_alter_file_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="height",
            field=models.IntegerField(default=2200),
        ),
        migrations.AlterField(
            model_name="file",
            name="width",
            field=models.IntegerField(default=1100),
        ),
    ]
