# Generated by Django 4.2.6 on 2023-11-17 07:54

from django.db import migrations, models
import pigeon_package_main_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_main_app", "0004_alter_file_height_alter_file_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pictureobject",
            name="picture",
            field=models.ImageField(
                null=True,
                upload_to=pigeon_package_main_app.models.get_picture_object_filepath,
            ),
        ),
    ]
