# Generated by Django 4.2.6 on 2023-11-09 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_main_app", "0005_packageinvitation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="packageinvitation",
            old_name="project",
            new_name="package",
        ),
    ]
