# Generated by Django 4.2.6 on 2023-11-17 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_main_app", "0005_alter_pictureobject_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="image_objects",
            new_name="picture_objects",
        ),
    ]
