# Generated by Django 4.2.6 on 2023-11-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_main_app", "0006_rename_image_objects_file_picture_objects"),
    ]

    operations = [
        migrations.AddField(
            model_name="pictureobject",
            name="order",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="textobject",
            name="order",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
