# Generated by Django 4.2.6 on 2023-11-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pigeon_package_main_app", "0007_pictureobject_order_textobject_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pictureobject",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="textobject",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
