# Generated by Django 4.2.6 on 2023-11-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pigeon_package_main_app",
            "0008_alter_pictureobject_order_alter_textobject_order",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pictureobject",
            name="name",
            field=models.CharField(default="layer", max_length=100),
        ),
        migrations.AddField(
            model_name="textobject",
            name="name",
            field=models.CharField(default="layer", max_length=100),
        ),
    ]
